// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuthenticationSchema from "@/models/drizzle/authentication.model";
import * as MediaSchema from "@/models/drizzle/media.model";

const schema = {
	...AuthenticationSchema,
	...MediaSchema
};

export default schema;
