// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuthSchema from "../models/drizzle/auth.model";
import * as MediaSchema from "../models/drizzle/media.model";

const schema = {
	...AuthSchema,
	...MediaSchema
};

export default schema;
